name: World Population App
on: push

jobs:
  build:
    name: World Population action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge App
          docker pull mongo
          docker run -d --name mongo-dbserver --network App mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t App .
      - name: Run image
        run: docker run --network App --name semcontainer App
      - name: view logs
        run: docker logs semcontainer
